site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand    
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  highlightjs: true
  hljs_languages:
    - lua

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
      permalink: true   

plugins:
  - search
  - tags

extra_javascript:
  - javascripts/tags.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - Introduction: Home/index.md
    - Installation: Home/installation.md
    - Examples:
      - Input: Home/examples/input.md